<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PianoPractice.Desktop</RootNamespace>
    <AssemblyName>PianoPractice.Desktop</AssemblyName>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\Verovio\**\*" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Bravura\**\*" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
